name: 'football_civica'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  +transient: false
  football_civica:
    staging:
      +database: "{{ env_var('DBT_ENVIRONMENTS') }}_SILVER_DB"
      +materialized: view
      Football:
        +materialized: view
      base:
        +materialized: ephemeral
    intermediate:
      +database: "{{ env_var('DBT_ENVIRONMENTS') }}_GOLD_DB"
      +materialized: ephemeral
    marts:
      +database: "{{ env_var('DBT_ENVIRONMENTS') }}_GOLD_DB"
      +materialized: table
      core:
        +materialized: view
      scorers:
        +materialized: view
      ranking:
        +materialized: view
      stats:
        +materialized: view

seeds:
  +schema: seed_data
  +database: "{{ env_var('DBT_ENVIRONMENTS') }}_BRONZE_DB"

snapshots:
  +transient: false
  +target_database: "{{ env_var('DBT_ENVIRONMENTS') }}_SILVER_DB"
  +target_schema: snapshots
