name: 'football_civica'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  +transient: false
  football_civica:
    staging:
      Football:
        +database: "{{ env_var('DBT_ENVIRONMENTS') }}_SILVER_DB"
        +materialized: view
        base:
          +database: "{{ env_var('DBT_ENVIRONMENTS') }}_SILVER_DB"
          +materialized: view
    intermediate:
        +database: "{{ env_var('DBT_ENVIRONMENTS') }}_GOLD_DB"
        +materialized: view
    marts:
        +materialized: table
        +database: "{{ env_var('DBT_ENVIRONMENTS') }}_GOLD_DB"
        core:
          +database: "{{ env_var('DBT_ENVIRONMENTS') }}_GOLD_DB"
          +materialized: view

seeds:
  +schema: seed_data
  +database: "{{ env_var('DBT_ENVIRONMENTS') }}_BRONZE_DB"

snapshots:
  +transient: false
  +target_database: "{{ env_var('DBT_ENVIRONMENTS') }}_SILVER_DB"
  +target_schema: snapshots
